server:
  port: 8086
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8091/eureka/
management:
  endpoints:
    web:
      exposure:
        include: "*"
spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/transactionDomain