server:
  port: 8082
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8091/eureka/
management:
  endpoints:
    web:
      exposure:
        include: "*"
spring:
  data:
    mongodb:
      database: customerDomain
      uri: mongodb://localhost:27017/customerDomain
      auto-index-creation: true
