server:
  port: 8083
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8091/eureka/
management:
  endpoints:
    web:
      exposure:
        include: "*"
spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/productDomain

maintenance:
  fee:
    savings: -1
    checkingAccount: 0.05
    fixedTerm: -1
monthly:
  commission:
    limit:
      savings: 5
      checkingAccount: -1
      fixedTerm: 1
