server:
  port: 8087
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8091/eureka/
management:
  endpoints:
    web:
      exposure:
        include: "*"
spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/yankiDomain
  kafka:
    consumer:
      bootstrap-servers: localhost:9092
#      group-id: group_id
#      auto-offset-reset: earliest
#      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
#      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
#    producer:
#      bootstrap-servers: localhost:9092
#      key-serializer: org.apache.kafka.common.serialization.StringSerializer
#      value-serializer: org.apache.kafka.common.serialization.StringSerializer